### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by zwjnju** [XikunLiu-huskit/GLIO#12]
Hi,
When I start GLIO, the problem below comes out:
![GLIO2](https://github.com/user-attachments/assets/3460e3bd-c557-4a0a-8015-5699e83a1cc4)

Is there any mistake in Estimator node?

**Comment by pangchenglin** [comment]
I met the same problem. Did you solved this problem?

**Comment by XikunLiu-huskit** [comment]
Hi @zwjnju, sorry for the late reply, it seems like you are using Noetic instead of Melodic to run the code. You will need some simple modifications to do so. Have you tried Docker? Let me know if you still need help.

**Comment by abstig** [comment]
> Hi, When I start GLIO, the problem below comes out: ![GLIO2](https://github.com/user-attachments/assets/3460e3bd-c557-4a0a-8015-5699e83a1cc4)
> 
> Is there any mistake in Estimator node?

**Comment by abstig** [comment]
i do ! have you solved it ?

**Comment by shizhinian** [comment]
> Hi [@zwjnju](https://github.com/zwjnju), sorry for the late reply, it seems like you are using Noetic instead of Melodic to run the code. You will need some simple modifications to do so. Have you tried Docker? Let me know if you still need help.

你好，我也遇到了相同问题，请问具体要调整哪些地方呢？

**Comment by XikunLiu-huskit** [comment]
Hi @zwjnju @abstig @shizhinian @pangchenglin, please try adding `return true`; at the end of the function `gnssraw2SO`, see if it can help. Please let me know if you have further issue.

**Comment by shizhinian** [comment]
> Hi [@zwjnju](https://github.com/zwjnju) [@abstig](https://github.com/abstig) [@shizhinian](https://github.com/shizhinian) [@pangchenglin](https://github.com/pangchenglin), please try adding `return true`; at the end of the function `gnssraw2SO`, see if it can help. Please let me know if you have further issue.

感谢您的回复，添加 `return true` 的确解决了 `free() double detected in tcache 2` 的问题!但是在后续播包时又出现了另外的问题，为了排查原因，我在 `CMakeLists.txt` 添加 `-fsanitize=address` 标志后运行报错如下：
```bash
==6631==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62a0000001f8 at pc 0x55555557a763 bp 0x7fffff9df4b0 sp 0x7fffff9df4a0
READ of size 8 at 0x62a0000001f8 thread T0
    #0 0x55555557a762 in Eigen::internal::handmade_aligned_free(void*) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:98
    #1 0x55555557a762 in Eigen::internal::aligned_free(void*) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:179
    #2 0x55555557a762 in Eigen::aligned_allocator<pcl::PointXYZI>::deallocate(pcl::PointXYZI*, unsigned long) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:763
    #3 0x55555557a762 in std::allocator_traits<Eigen::aligned_allocator<pcl::PointXYZI> >::deallocate(Eigen::aligned_allocator<pcl::PointXYZI>&, pcl::PointXYZI*, unsigned long) /usr/include/c++/9/bits/alloc_traits.h:332
    #4 0x55555557a762 in std::_Vector_base<pcl::PointXYZI, Eigen::aligned_allocator<pcl::PointXYZI> >::_M_deallocate(pcl::PointXYZI*, unsigned long) /usr/include/c++/9/bits/stl_vector.h:351
    #5 0x55555557a762 in std::_Vector_base<pcl::PointXYZI, Eigen::aligned_allocator<pcl::PointXYZI> >::~_Vector_base() /usr/include/c++/9/bits/stl_vector.h:332
    #6 0x55555557a762 in std::vector<pcl::PointXYZI, Eigen::aligned_allocator<pcl::PointXYZI> >::~vector() /usr/include/c++/9/bits/stl_vector.h:680
    #7 0x55555557a762 in pcl::PointCloud<pcl::PointXYZI>::~PointCloud() /usr/include/pcl-1.10/pcl/point_cloud.h:180
    #8 0x5555555d1f7e in Preprocessing::cloudHandler(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&) /home/x/GLIO/src/GLIO/src/Preprocessing.cpp:637
    #9 0x5555555715d6 in boost::_mfi::mf1<void, Preprocessing, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>::operator()(Preprocessing*, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&) const /usr/include/boost/bind/mem_fn_template.hpp:165
    #10 0x5555555715d6 in void boost::_bi::list2<boost::_bi::value<Preprocessing*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, Preprocessing, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>, boost::_bi::rrlist1<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, Preprocessing, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>&, boost::_bi::rrlist1<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>&, int) /usr/include/boost/bind/bind.hpp:319
    #11 0x5555555715d6 in void boost::_bi::bind_t<void, boost::_mfi::mf1<void, Preprocessing, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<Preprocessing*>, boost::arg<1> > >::operator()<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&) /usr/include/boost/bind/bind.hpp:1306
    #12 0x5555555715d6 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Preprocessing, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<Preprocessing*>, boost::arg<1> > >, void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&) /usr/include/boost/function/function_template.hpp:158
    #13 0x5555555a6fed in boost::function1<void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>::operator()(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&) const /usr/include/boost/function/function_template.hpp:763
    #14 0x5555555a6fed in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) /usr/include/boost/function/function_template.hpp:158
    #15 0x5555555df6e6 in boost::function1<void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >::operator()(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) const /usr/include/boost/function/function_template.hpp:763
    #16 0x5555555df6e6 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) /opt/ros/noetic/include/ros/subscription_callback_helper.h:144
    #17 0x7fffec7a9138 in ros::SubscriptionQueue::call() (/opt/ros/noetic/lib/libroscpp.so+0x158138)
    #18 0x7fffec757171 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) (/opt/ros/noetic/lib/libroscpp.so+0x106171)
    #19 0x7fffec758882 in ros::CallbackQueue::callAvailable(ros::WallDuration) (/opt/ros/noetic/lib/libroscpp.so+0x107882)
    #20 0x7fffec7abfce in ros::SingleThreadedSpinner::spin(ros::CallbackQueue*) (/opt/ros/noetic/lib/libroscpp.so+0x15afce)
    #21 0x7fffec79421e in ros::spin() (/opt/ros/noetic/lib/libroscpp.so+0x14321e)
    #22 0x55555556fef1 in main /home/x/GLIO/src/GLIO/src/Preprocessing.cpp:678
    #23 0x7fffebe0f082 in __libc_start_main ../csu/libc-start.c:308
    #24 0x55555557036d in _start (/home/x/GLIO/devel/lib/GLIO/Preprocessing+0x1c36d)

0x62a0000001f8 is located 8 bytes to the left of 21728-byte region [0x62a000000200,0x62a0000056e0)
allocated by thread T0 here:
    #0 0x7ffff750d808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7ffff3316c2c in Eigen::internal::aligned_malloc(unsigned long) (/lib/x86_64-linux-gnu/libpcl_filters.so.1.10+0x316c2c)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/eigen3/Eigen/src/Core/util/Memory.h:98 in Eigen::internal::handmade_aligned_free(void*)
Shadow bytes around the buggy address:
  0x0c547fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c547fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c547fff8000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c547fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c547fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c547fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c547fff8040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c547fff8050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c547fff8060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c547fff8070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c547fff8080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==6631==ABORTING
```
另外，如果将 `Preprocessing.cpp` 中第 648-654 行代码进行修改（仅仅是为了测试去掉下采样操作会是什么结果）：
```C++
  // pcl::PointCloud<PointType> surfPointsLessFlatScanDS;
  // pcl::VoxelGrid<PointType> downSizeFilter;
  // downSizeFilter.setInputCloud(surfPointsLessFlatScan);
  // downSizeFilter.setLeafSize(ds_v, ds_v, ds_v);
  // downSizeFilter.filter(surfPointsLessFlatScanDS);
  // surfPointsLessFlat += surfPointsLessFlatScanDS;
  surfPointsLessFlat += *surfPointsLessFlatScan;
```
如上，程序就不报错了，这让我实在不知道问题出在哪了
